
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: team01-w24-4pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"Tyler-University","number":26,"title":"Add University Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/26"},{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-JokeQuery-Controller","number":25,"title":"Arnav joke query controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/25"},{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-JokeQueryService","number":24,"title":"Arnav joke query service","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/24"},{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ-Zipcode","number":23,"title":"AJ - Add ZipCode Service and Tests","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/23"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"Likhit-Location-Controller","number":21,"title":"Add location controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/21"},{"author":{"id":"U_kgDOBdHZtA","is_bot":false,"login":"alexanderthomasucsb","name":""},"headRefName":"Alex-TidesService-Controller","number":20,"title":"Alex tides service controller","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/20"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"Likhit-Location","number":19,"title":"Add Location Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/19"},{"author":{"id":"U_kgDOBdHZtA","is_bot":false,"login":"alexanderthomasucsb","name":""},"headRefName":"Alex-TidesService","number":18,"title":"AT - Add TidesQuery Service","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/18"}]
