
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team01-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: team01-w24-4pm-1
pull_requests: [{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"revert-35-Chris-PublicHoliday2","number":36,"title":"Revert \"Chris public holiday2\"","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/36"},{"author":{"id":"U_kgDOCU6okQ","is_bot":false,"login":"chrisriney4","name":""},"headRefName":"Chris-PublicHoliday","number":34,"title":"Chris public holiday","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/34"},{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"revert-31-Likhit-HomeController","number":33,"title":"Revert \"LG - home controller\"","url":"https://github.com/ucsb-cs156-w24/team01-w24-4pm-1/pull/33"}]
